name: update-aur.yml
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. ttl-v0.6.9)"
        required: true

jobs:
  update-aur-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi
      - name: Generate PKGBUILDs
        run: bash scripts/generate_linux_pkgs.sh "${{ env.VERSION }}" aur
      - name: Publish AUR package (twintaillauncher-bin)
        if: success()
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: twintaillauncher-bin
          pkgbuild: ./ttl-bin/PKGBUILD
          commit_username: ${{ secrets.GIT_USER }}
          commit_email: ${{ secrets.GIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - name: Publish AUR package (twintaillauncher)
        if: success()
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: twintaillauncher
          pkgbuild: ./ttl-stable-src/PKGBUILD
          commit_username: ${{ secrets.GIT_USER }}
          commit_email: ${{ secrets.GIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
      - name: Publish AUR package (twintaillauncher-git)
        if: success()
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: twintaillauncher-git
          pkgbuild: ./ttl-git/PKGBUILD
          commit_username: ${{ secrets.GIT_USER }}
          commit_email: ${{ secrets.GIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
